const express = require('express')
const bodyParser = require('body-parser')
const sequelize = require('./util/database')
const passport = require('passport')
const adminRoute = require('./routes/admin//admin.routes')
const shopRoute = require('./routes/shop/shop.routes')
const userRoute = require('./routes/user/user.routes')
const User = require('./models/user/user.model')
const Product = require('./models/admin/product.model')
const Cart = require('./models/shop/cart.model')
const cartItem = require('./models/shop/cart-item.model')
const app = express()
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({extended: false}))
app.use(passport.initialize())
app.use('/admin', adminRoute)
app.use('/shop', shopRoute)
app.use('/customer', userRoute)
Product.belongsTo(User, {constraints: false, onDelete: 'CASCADE'})
User.hasMany(Product)
User.hasOne(Cart)
Cart.belongsTo(User)
Product.belongsToMany(Cart, {through: cartItem})
Cart.belongsToMany(Product, {through: cartItem})
sequelize
//.sync({force: true})
.sync()
.then(result=>{
    app.listen(3000, ()=>console.log('server is runing'))
}).catch(err=>console.log(err))

